// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  algoliaAppId: '7LOP7PA3QP',
  algoliaSearchApiKey: 'ee94ab6f55a21150ac1ae1316dbdc467',
  algoliaRecordingsIndex: 'prod_recordings',
  algoliaShowsIndex: 'prod_shows',
  algoliaArtistsIndex: 'prod_artists',
  production: true,
  environment: 'production',
  version: env.npm_package_version,
  serverUrl: 'https://api.radio-rasclat.com',
  defaultLanguage: 'EN',
  supportedLanguages: ['DE', 'EN', 'FR'],
};
